# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lsl0

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_e568ce4b10ca49deb7f6e613594eb74e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_12e86db6ce634274a1bf1bac3b68c92c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e568ce4b10ca49deb7f6e613594eb74e }}/ngnix:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lsl0'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fb50509175f64f0584636b54d843dd13 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e568ce4b10ca49deb7f6e613594eb74e }}/ngnix:${{ github.sha }}'